baseURL = 'https://heatherhzli.com'
languageCode = 'en-uk'
title = 'Heather Li | heatherhzli.com'
theme = 'hugo-theme-console'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # navlinks
  [[params.navlinks]]
  name = "projects/"
  url = "projects/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  #description
  description = "The personal website of Heather Li, a final year student at the University of Oxford!"

  #favicon
  favicon = "img/favicon/favicon.ico"
  
[taxonomies]
   tag = "tags"
